### ISSUE TITLE
멤버 수정 및 탈퇴

### ISSUE THREAD

**Issue by musicmalgon** [2ven-team-project/2ven-concurrency-control#14]
## Description

[PUT] /members/{memberId}
[DELETE] /members/{memberId}

설명
- 회원정보 수정 및 탈퇴

예외처리
- 알맞는 id가 없을시 예외처리
- 비밀번호가 일치하지 않을시 예외처리

Request Body
```json
{
   "email ":"email@naver.com",
   "name":"name",
   "password":"password"
} 
```

Response Body
```json
{
   "email ":"email@naver.com",
   "name":"name",
}
```

응답코드
`200, OK`

**Comment by loadkrnis** [comment]
[PUT] /members/{memberId}
