### ISSUE TITLE
쿠폰 생성

### ISSUE THREAD

**Issue by syh21133** [2ven-team-project/2ven-concurrency-control#3]
## Description
[Post] /coupon

설명
- 관리자가 쿠폰 생성

예외처리
- memberRole 이 admin이 아닐시 예외처리

Request Body
```json
"name" : "쿠폰이름",
"count" : "발급할 갯수",
"discount" : "할인가격"
```

Response Body
```json

```

응답코드
`200. OK`

**Comment by JANG-MINWOO** [comment]
할인가격의 상한선같은 부분도 잡아서 예외처리를 해야할것 같습니다
